touch.icons:
	convert touch-icon.png -resize 144x144 icon_144x144.png
	convert touch-icon.png -resize 114x114 icon_114x114.png
	convert touch-icon.png -resize 72x72 icon_72x72.png
	convert touch-icon.png -resize 57x57 icon_57x57.png
	convert touch-icon.png -resize 96x96 icon_96x96.png
	convert touch-icon.png -resize 48x48 icon_48x48.png
	convert touch-icon.png -resize 58x58 icon_58x58.png
	convert touch-icon.png -resize 29x29 icon_29x29.png

splash.screens:
	convert launch-screen-source.png -resize 1496x2048\! apple-touch-startup-image-1496x2048.png
	convert launch-screen-source.png -resize 748x1024\! apple-touch-startup-image-748x1024.png
	convert launch-screen-source.png -resize 768x1004\! apple-touch-startup-image-768x1004.png
	convert launch-screen-source.png -resize 640x920\! apple-touch-startup-image-640x920.png
	convert launch-screen-source.png -resize 320x460\! apple-touch-startup-image-320x460.png
